### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [BogaevskiyDm/my-grid-template-project#1]
1)
элементы используются вне блока
![image](https://user-images.githubusercontent.com/8464662/111746964-645a2280-8897-11eb-9a3b-327b73f8cc6b.png)

2)
странные, непонятные, бессмысленные названия классов
![image](https://user-images.githubusercontent.com/8464662/111747088-894e9580-8897-11eb-82ec-d06c6fd12863.png)
![image](https://user-images.githubusercontent.com/8464662/111747164-ac794500-8897-11eb-8da9-5ab89e99c1cd.png)
![image](https://user-images.githubusercontent.com/8464662/111747200-b4d18000-8897-11eb-8620-1c8a2a878ae1.png)
![image](https://user-images.githubusercontent.com/8464662/111747253-c74bb980-8897-11eb-907a-d2c6ec7751e2.png)

вот вам проблема использования destop first
![image](https://user-images.githubusercontent.com/8464662/111747433-fe21cf80-8897-11eb-9b3d-68200152148b.png)
куча перечеркивания и как следствие - кнопки незначительно смещены
![image](https://user-images.githubusercontent.com/8464662/111747555-1eea2500-8898-11eb-8ebc-7b88a3c4426e.png)

4)
цвет placeholder не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/111747626-345f4f00-8898-11eb-91a1-5697735a15da.png)

**Comment by Alecto** [comment]
1 - не исправлено, в коде полно таких ошибок
![image](https://user-images.githubusercontent.com/8464662/111785950-ebbe8a80-88c5-11eb-9751-234e863973f0.png)
и тд

2 - аналогично, принято составные слова разделять -

5)
элемент не может вкладываться в элемент, повторите БЭМ.
![image](https://user-images.githubusercontent.com/8464662/111786119-1f011980-88c6-11eb-9c10-300499e69f1d.png)

**Comment by BogaevskiyDm** [comment]
Доброй ночи. Всё, что было не по бэм- поменял. Sent from my Galaxy
-------- Original message --------From: Andrey ***@***.***> Date: 3/19/21  16:17  (GMT+03:00) To: BogaevskiyDm/my-grid-template-project ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [BogaevskiyDm/my-grid-template-project] работа над ошибками (#1) 

1 - не исправлено, в коде полно таких ошибок



и тд

2 - аналогично, принято составные слова разделять -







элемент не может вкладываться в элемент, повторите БЭМ.

**Comment by Alecto** [comment]
в письме нет 2х ссылок, так что проверить не могу

сб, 20 мар. 2021 г. в 01:36, BogaevskiyDm ***@***.***>:

**Comment by BogaevskiyDm** [comment]
https://github.com/BogaevskiyDm/my-grid-template-project/pulse
https://bogaevskiydm.github.io/my-grid-template-project/


Sent from Mail for Windows 10

**Comment by Alecto** [comment]
отлично, работа принята.
